name = "image-background-remover"
compatibility_date = "2025-01-01"
pages_build_output_dir = ".open-next/assets"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "image-background-remover-cache"
