name = "image-background-remover"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"

[[kv_namespaces]]
binding = "PKCE_VERIFIERS"
id = "07fda2f5863949d7b38e176e819d65b6"

[[kv_namespaces]]
binding = "USER_DATA"
id = "4fe5b29d54b341aaae66dd332d8f78ba"

